"""update columns tables

Revision ID: 2fca44c316ae
Revises: 7e1623c5b963
Create Date: 2026-03-26 10:55:51.451534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fca44c316ae'
down_revision: Union[str, Sequence[str], None] = '7e1623c5b963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'])
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'extra_data')
    op.drop_column('documents', 'content')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'document_id')
    # ### end Alembic commands ###
