"""change vector dimension

Revision ID: 5f15bc208422
Revises: fa4b123d285d
Create Date: 2026-05-11 18:11:09.631867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '5f15bc208422'
down_revision: Union[str, Sequence[str], None] = 'fa4b123d285d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=Vector(dim=512),
               type_=Vector(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=Vector(dim=1024),
               type_=Vector(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
